version: 0.2

phases:
    install:
        commands:
            - apt-get update
            - apt-get install docker.io -y
    pre_build:
        commands:
            - $(aws ecr get-login --no-include-email)
    build:
        commands:
            - docker build --tag 278088188282.dkr.ecr.us-east-2.amazonaws.com/semantive:latest .
    post_build:
        commands:
            - docker push 278088188282.dkr.ecr.us-east-2.amazonaws.com/semantive:latest

